Annihilate offline servers!

diff --git a/bin/minecraft-server-list b/bin/minecraft-server-list
--- a/bin/minecraft-server-list
+++ b/bin/minecraft-server-list
@@ -14,8 +14,14 @@ NAMES=()
 
 RUNNING=$(sdc-listmachines --tag minecraft=* | \
     json -ga primaryIp state tags.minecraft)
+if [[ $? -ne 0 ]]; then
+    fatal "Unable to find running servers."
+fi
 
 MANTA=$(mls $MANTA_LOCATION | tr -d '/' | xargs -n 1 echo "n/a offline")
+if [[ $? -ne 0 ]]; then
+        fatal "Unable to find offline servers."
+fi
 
 printf "$PATTERN" "IP" "STATE" "NAME"
 echo
