Check for errors.

diff --git a/bin/minecraft-server-launch b/bin/minecraft-server-launch
--- a/bin/minecraft-server-launch
+++ b/bin/minecraft-server-launch
@@ -1,12 +1,19 @@
-#! /usr/bin/bash
+#!/usr/bin/env bash
+# -*- mode: shell-script; fill-column: 80; -*-
+#
+# Copyright (c) 2013 Joyent Inc., All rights reserved.
+#
 
-# Assume that SDC environment variables are set:
-# export SDC_URL=https://us-east-1.api.joyentcloud.com
-# export SDC_ACCOUNT=Joyent_Dev
-# export SDC_KEY_ID=3e:37:9b:11:a6:dc:21:be:1a:fd:95:b6:73:ea:42:9e
 
+source $(dirname $0)/common.sh
 
-SERVERNAME="coolserver"
+usage() { echo "Usage: $0 [server-name]" 1>&2; exit 1; }
+
+if [ "$#" -ne 1 ]; then
+    usage
+fi
+
+SERVERNAME="$1"
 
 IMAGEID=17c98640-1fdb-11e3-bf51-3708ce78e75a
 #	{
@@ -38,15 +45,20 @@ PACKAGENAME=g3-standard-4-smartos-image-creation
 # TODO
 
 
-echo "Creating ${SERVERNAME}"
+echo -n "Creating ${SERVERNAME} ."
 SERVERID=$(sdc-createmachine	--dataset $IMAGEID \
 								--package $PACKAGENAME \
 								--tag "minecraft=${SERVERNAME}" | json id)
-echo $SERVERID
+if [ -z $SERVERID ] ; then 
+	fatal "Can't provision."
+fi
+
 while [[ $(sdc-getmachine $SERVERID | json state) ==  "provisioning" ]]
 	do
-		echo "provisioning"
+		echo -n "."
+		sleep 1
 	done
 
+echo "done"
 
 
